# =========================
# APP
# =========================
spring.application.name=app-inclusiva-backend
server.port=8080

# =========================
# POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/app_inclusiva
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Sugerido por Hibernate 7 / Spring Boot 4
jakarta.persistence.jdbc.url=jdbc:postgresql://localhost:5432/app_inclusiva
jakarta.persistence.jdbc.user=postgres
jakarta.persistence.jdbc.password=123

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=postgresql
spring.jpa.open-in-view=false

# =========================
# LOG SQL (opcional pero útil)
# =========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
app.jwt.secret=mi_clave_super_secreta_backend_2026_uteq_angular_seguridad_12345
app.jwt.expiration-minutes=60

# CORS (Angular dev)
app.cors.allowed-origins=http://localhost:4200